### ISSUE TITLE
Approximate time to release codes

### ISSUE THREAD

**Issue by volgachen** [encounter1997/FP-DETR#1]
Thanks for your great works!
This work attracts my attention, and I am curious of the implementation. 
I wonder when will you release the code.
Thanks.

**Comment by encounter1997** [comment]
Hi, thanks for your interest. 
We plan to release the code next week. Stay tuned!

**Comment by volgachen** [comment]
Thanks for reply.
I have a minor problem on implementation. How do you process the 300 object queries with Deformable Transformer Encoder? Do you treat them as 300 additional feature levels with only one resolution or in some other way?

**Comment by encounter1997** [comment]
> Thanks for reply. I have a minor problem on implementation. How do you process the 300 object queries with Deformable Transformer Encoder? Do you treat them as 300 additional feature levels with only one resolution or in some other way?

Yes, we treated the 300 queries as an additional feature level and masked the information flow from the queries.

**Comment by volgachen** [comment]
Got it. Thanks!

I am looking for forward to studying your code :-)

**Comment by encounter1997** [comment]
> Got it. Thanks!
> 
> I am looking for forward to studying your code :-)

Hi, the code is now available~

**Comment by volgachen** [comment]
> > Got it. Thanks!
> > I am looking for forward to studying your code :-)
> 
> Hi, the code is now available~

Thanks for notification!

**Comment by volgachen** [comment]
> > Got it. Thanks!
> > I am looking for forward to studying your code :-)
> 
> Hi, the code is now available~

Thanks for notification!
